name: CI

on:
  workflow_dispatch:
  push:
    branches: ['**']
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug, Release]
        include:
          - os: windows-latest
            cmake_generator: "Visual Studio 17 2022"
          - os: ubuntu-latest
            cmake_generator: "Unix Makefiles"
          - os: macos-latest
            cmake_generator: "Unix Makefiles"

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: '0'

    - name: Configure CMake
      shell: bash
      run: |
        cmake -S "${{github.workspace}}" \
              -B "${{github.workspace}}/build" \
              -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
              -G "${{matrix.cmake_generator}}" 

    - name: Build
      shell: bash
      run: |
        cmake --build "${{github.workspace}}/build" \
              --config ${{matrix.build_type}} \
              --parallel

    - name: Set Test Executable Permissions
      if: runner.os != 'Windows'
      shell: bash
      run: |
        chmod +x build/lib/test/lib_unit_tests
        chmod +x build/app/test/backend_unit_tests

    - name: Run Unit Tests
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: |
        ctest -C ${{matrix.build_type}} \
              -L unit \
              --output-on-failure \
              --output-junit unit-test-results.xml \
              --parallel
      continue-on-error: true

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      if: always()
      with:
        files: |
          build/unit-test-results.xml
        check_name: "Unit Test Results (${{ matrix.os }}-${{ matrix.build_type }})"
        comment_mode: always  # Set to 'always' if you want PR comments


    # TODO: Configure to upload binaries for CD pipeline
   # - name: Upload Build Artifacts
   #   uses: actions/upload-artifact@v4
   #   with:
   #     name: build-${{ matrix.os }}-${{ matrix.build_type }}
   #     path: build/
   #     retention-days: 32  # Adjust as needed


